include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:

analyzer:
  errors:
    flutter_style_todos: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  plugins:
    - custom_lint
